# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0
AWSTemplateFormatVersion: "2010-09-09"
Description: "CloudFormation template for a Hello World Lambda function using Node.js"
Resources:
  # IAM Role for Lambda execution
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole

  # Lambda Function
  HelloWorldFunction:
    # checkov:skip=CKV_AWS_117
    # checkov:skip=CKV_AWS_116
    # checkov:skip=CKV_AWS_115
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: hello-world-function
      Runtime: nodejs22.x
      Handler: index.handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Code:
        ZipFile: |
          exports.handler = async (event, context) => {
              console.log('Hello World!');
              const response = {
                  statusCode: 200,
                  body: JSON.stringify('Hello World!')
              };
              return response;
          };
      Timeout: 30
      MemorySize: 128
    Metadata:
      guard:
        SuppressedRules:
          - id: "LAMBDA_DLQ_CHECK"
            reason: "Just providing an example of Lambda"
          - id: "LAMBDA_INSIDE_VPC"
            reason: "Just providing an example of Lambda"
          - id: "LAMBDA_CONCURRENCY_CHECK"
            reason: "Just providing an example of Lambda"

Outputs:
  LambdaFunctionArn:
    Description: ARN of the Lambda function
    Value: !GetAtt HelloWorldFunction.Arn
